In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [2]:
# File for data file
file_path = "~/Documents/BedTracks/git_test/Crime_Data_from_2020_to_Present.csv"

In [3]:
# Reading .csv file
dataframe = pd.DataFrame(pd.read_csv(file_path))
# Formatting date-time columns
dataframe["Date Rptd"] = pd.to_datetime(dataframe["Date Rptd"], format='%m/%d/%Y %H:%M:%S %p')
dataframe["DATE OCC"] = pd.to_datetime(dataframe["Date Rptd"])

In [13]:
# Showing top rows 
pd.set_option("display.max_columns", len(dataframe))
pd.set_option("display.max_rows", 4)
dataframe

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,Mocodes,Vict Age,Vict Sex,Vict Descent,Premis Cd,Premis Desc,Weapon Used Cd,Weapon Desc,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,10304468,2020-01-08 12:00:00,2020-01-08 12:00:00,2230,3,Southwest,377,2,624,BATTERY - SIMPLE ASSAULT,0444 0913,36,F,B,501.0,SINGLE FAMILY DWELLING,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",AO,Adult Other,624.0,NaN,NaN,NaN,1100 W 39TH PL,NaN,34.0141,-118.2978
1,190101086,2020-01-02 12:00:00,2020-01-02 12:00:00,330,1,Central,163,2,624,BATTERY - SIMPLE ASSAULT,0416 1822 1414,25,M,H,102.0,SIDEWALK,500.0,UNKNOWN WEAPON/OTHER WEAPON,IC,Invest Cont,624.0,NaN,NaN,NaN,700 S HILL ST,NaN,34.0459,-118.2545
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
752909,231210064,2023-04-12 12:00:00,2023-04-12 12:00:00,1630,12,77th Street,1239,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",0601 0445 0416 0359,29,M,B,222.0,LAUNDROMAT,500.0,UNKNOWN WEAPON/OTHER WEAPON,IC,Invest Cont,230.0,NaN,NaN,NaN,6100 S VERMONT AV,NaN,33.9841,-118.2915
752910,230906458,2023-03-05 12:00:00,2023-03-05 12:00:00,900,9,Van Nuys,914,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),0329 1822,53,F,H,502.0,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",NaN,NaN,IC,Invest Cont,745.0,NaN,NaN,NaN,14500 HARTLAND ST,NaN,34.1951,-118.4487

In [14]:
# Reseting viz options
pd.reset_option("display.max_columns")
pd.reset_option("display.max_rows")

In [15]:
# Top locations where crimes took place and total # of crimes
pd.DataFrame(dataframe["Premis Desc"].value_counts()).head(10)

                                              Premis Desc
STREET                                             189365
SINGLE FAMILY DWELLING                             127887
MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)        92606
PARKING LOT                                         53362
OTHER BUSINESS                                      35108
SIDEWALK                                            32553
VEHICLE, PASSENGER/TRUCK                            22605
GARAGE/CARPORT                                      15229
DRIVEWAY                                            12624
RESTAURANT/FAST FOOD                                 9565